server.port: 8222

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/risks?useSSL=false
    username: risks_usr
    password: Qwe123!
    driverClassName: com.mysql.jdbc.Driver
    #schema: risks
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  redis:
    host: 192.168.1.8
    port: 6379

logging:
  level:
    org.springframework.security: DEBUG

flyway:
  enabled: true
  baseline-version: 0.1

security:
  sessions: ALWAYS

